name: Push to Artifact Registry

on:
  push:
    branches: ["main"]

# env:
#   IMAGE_NAME: "my-app-image"
#   PROJECT_ID: "rpi-hub-438905"
#   AR_REPO_LOCATION: "asia-southeast1"
#   AR_URL: "asia-southeast1-docker.pkg.dev/rpi-hub-438905/piso-wifi-repository"
#   SERVICE_ACCOUNT: "422041495987-compute@developer.gserviceaccount.com"
#   WORKLOAD_IDENTITY_PROVIDER: "projects/422041495987/locations/global/workloadIdentityPools/piso-wifi-dev-pool/providers/github-actions-provider"

jobs:
  job_id:
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"
