name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          project_id: "rpi-hub-438905"
          workload_identity_provider: "projects/422041495987/locations/global/workloadIdentityPools/oidc-pool/providers/github"

      - name: Run gcloud command
        run: |
          gcloud auth list
          gcloud compute instances list  # Example command
